# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shapeShare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Administrative Data', 'Administrative Data'), ('Environmental data', 'Environmental data'), ('Development data', 'Development data')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='shapefile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shapeShare.Category'),
        ),
    ]
